site_name: Pre-Commit in 5 minutes
site_author: Michal Mazurek
site_description: How to use github pre-commit hooks in 5 minutes.
repo_url: https://github.com/MichalMazurek/pre-commit-talk.mm-python.ninja
copyright: Copyright © 2019 Michal Mazurek
nav:
  - Introduction: index.md
  - What are the git hooks?: what-are-the-git-hooks.md
  - Wait... writing scripts?: wait-writing-scripts.md
  - So why I need it?: why-i-need-it.md
  - Introducing pre-commit.com: introducing-pre-commit-com.md
  - Using it: using-it.md
  - Using it - continued: using-it-2.md
  - Using it - finishing: using-it-3.md
  - It benefits your python project: it-benefits-your-python-project.md
  - That's all!: thanks.md
theme:
  name: "material"

extra_javascript:
  - assets/keyhandler.js

markdown_extensions:
  - codehilite
  - admonition

plugins:
  - search
  - minify:
      minify_html: true
