site_name: Pre-Commit in 5 minutes
nav:
  - Introduction: index.md
  - What are the git hooks?: what-are-the-git-hooks.md
  - Wait... writing scripts?: wait-writing-scripts.md
  - So why I need it?: why-i-need-it.md
  - Introducing pre-commit.com: introducing-pre-commit-com.md
  - Using it: using-it.md
  - Using it - continued: using-it-2.md
  - It benefits your python project: it-benefits-your-python-project.md
theme:
  name: "material"
markdown_extensions:
  - codehilite
